version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    container_name: data_base
    environment:
      POSTGRES_USER: tutunovka
      POSTGRES_PASSWORD: tutun14232
      POSTGRES_DB: Tutunovka_DB
    ports:
      - "5432:5432"
