<<<<<<< HEAD
# Generated by Django 5.0.3 on 2024-04-03 10:55
=======
# Generated by Django 5.0.3 on 2024-04-02 22:04
>>>>>>> cd49764 (dots creation fixed & date in dots added)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutun_app', '0010_note_remove_privateroute_note_privateroute_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatedot',
            name='date',
<<<<<<< HEAD
            field=models.DateTimeField(default=None, null=True),
=======
            field=models.DateTimeField(default=None),
>>>>>>> cd49764 (dots creation fixed & date in dots added)
        ),
    ]
