# Generated by Django 5.0.3 on 2024-04-02 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutun_app', '0011_privatedot_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatedot',
            name='date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
