# Generated by Django 5.0.1 on 2024-04-29 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutun_app', '0011_complaint'),
        ('tutun_app', '0011_privatedot_date'),
    ]

    operations = [
    ]
