# Generated by Django 5.0.3 on 2024-04-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutun_app', '0012_merge_20240412_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateroute',
            name='len',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='privateroute',
            name='month',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='privateroute',
            name='year',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
