# Generated by Django 5.0.3 on 2024-05-04 15:28

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('tutun_app', '0012_merge_20240412_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateroute',
            name='length',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='privateroute',
            name='month',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='privateroute',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='privateroute',
            name='year',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
