# Generated by Django 5.0.3 on 2024-04-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutun_app', '0013_privateroute_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateroute',
            name='length',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='privateroute',
            name='month',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='privateroute',
            name='year',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
