# Generated by Django 5.0.3 on 2024-05-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutun_app', '0013_privateroute_length_privateroute_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateroute',
            name='note',
            field=models.ManyToManyField(null=True, to='tutun_app.note'),
        ),
    ]
