# Generated by Django 5.0.3 on 2024-05-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutun_app', '0014_alter_privateroute_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateroute',
            name='note',
            field=models.ManyToManyField(to='tutun_app.note'),
        ),
    ]
