# Generated by Django 5.0.3 on 2024-05-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutun_app', '0014_privateroute_length_privateroute_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicroute',
            name='length',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='publicroute',
            name='month',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='publicroute',
            name='year',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
