# Generated by Django 5.0.3 on 2024-04-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutun_app', '0014_rename_len_privateroute_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateroute',
            name='length',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='privateroute',
            name='month',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='privateroute',
            name='year',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
