# Generated by Django 5.0.4 on 2024-04-29 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tutun_app", "0013_privateroute_tags"),
        (
            "tutun_app",
            "0015_alter_privateroute_length_alter_privateroute_month_and_more",
        ),
    ]

    operations = []
