# Generated by Django 5.0.3 on 2024-04-12 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutun_app', '0010_publicroute_tags'),
        ('tutun_app', '0011_complaint'),
        ('tutun_app', '0011_privatedot_date'),
    ]

    operations = [
    ]
